eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8001/eurekaserver
            instance:
            preferIpAddress: true
spring:
    application:
        name: eurekaclient